Login vm sealed class
aditya-bhawsar-mutualmobile/PictureUpload pull request #5
Opened 2021-09-16 10:05 UTC by aditya-bhawsar-mutualmobile

Created A Sealed Class just to make sure all the different types of ui states are covered may need to add more later

2021-09-16 12:34 UTC, saurabh-mishra-mm requested changes

2021-09-16 12:34 UTC, saurabh-mishra-mm commented on app/src/test/java/com/example/pictureupload/LoginViewModelTest.kt
>      fun `checking what validate returns on input incorrect`(){
The name of this case could be more specific like `checking what validate returns on empty input`

2021-09-17 04:40 UTC, aditya-bhawsar-mutualmobile commented
hey there i have made the changes please have a look again @saurabh-mishra-mm

2021-09-22 10:59 UTC, saurabh-mishra-mm approved these changes

2021-09-23 05:25 UTC, closed without merging